---
# tasks file for ansible-frr
- name: Gather os specific variables
  include_vars: "{{ item }}"
  tags:
    - always
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Run FRR Tasks
  block:
   - include_tasks: debian.yml
     when:
       - ansible_distribution == "Debian"
       - frr_version|float is version("7.0", ">=")
   - include_tasks: debian_legacy.yml
     when:
       - ansible_distribution == "Debian"
       - frr_version|float is version("7.0", "<")
   - include_tasks: debian.yml
     when:
       - ansible_distribution == "Ubuntu"
       - frr_version|float is version("7.0", ">=")
   - include_tasks: debian_legacy.yml
     when:
       - ansible_distribution == "Ubuntu"
       - frr_version|float is version("7.0", "<")
   - include_tasks: redhat.yml
     when:
       - ansible_os_family == "RedHat"
       - frr_version|float is version("7.0", ">=")
   - include_tasks: redhat_legacy.yml
     when:
       - ansible_os_family == "RedHat"
       - frr_version|float is version("7.0", "<")
   - include_tasks: system_tuning.yml
   - include_tasks: config.yml
   - include_tasks: monitor.yml
     when:
       - frr_monitor == True
     tags:
       - frr-monitoring
  when: routing_type == "frr"

- include_tasks: quagga.yml
  when: routing_type == "quagga"
