---
- name: Remove FRR
  package:
    name: frr
    state: absent
  become: true

- name: Installing Quagga From Repo
  package:
    name: quagga
    state: present
  become: true

- name: config | Configuring daemons
  template:
    backup: yes
    src: etc/frr/daemons.j2
    dest: /etc/quagga/daemons
    owner: quagga
    group: quagga
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart quagga
    - start quagga

- name: config | Configuring vtysh.conf
  template:
    backup: yes
    src: etc/frr/vtysh.conf.j2
    dest: /etc/quagga/vtysh.conf
    owner: quagga
    group: quaggavty
    mode: u=rw,g=r,o=
  become: true
  notify:
    - restart quagga
    - start quagga

- name: config | Configuring debian.conf
  template:
    backup: yes
    src: etc/frr/debian.conf.j2
    dest: /etc/quagga/debian.conf
    owner: quagga
    group: quagga
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart quagga
    - start quagga
  when: ansible_os_family == "Debian"

- name: config | Configuring Quagga
  template:
    backup: yes
    src: etc/frr/frr.conf.j2
    dest: /etc/quagga/Quagga.conf
    owner: quagga
    group: quagga
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart quagga
    - start quagga
