---
- name: redhat | Installing Pre-Reqs
  yum:
    name: ["iproute", "sudo", "which"]
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Installing FRR repository
  yum:
    name: "{{ frr_rpm_repository }}"
    state: present
  become: true
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: redhat | Ensure Quagga is removed
  package:
    name: quagga
    state: absent
  become: true

- name: redhat | Installing FRR {{ frr_version }}
  yum:
    name:
      - frr
      - frr-pythontools
    state: present
  become: true
  notify:
    - restart frr
