---
- name: redhat | Installing Pre-Reqs
  yum:
    name: ["iproute", "sudo", "which"]
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Installing FRR repository
  yum:
    name: "{{ frr_rpm_repository }}"
    state: present
  become: true
  when:
    - (ansible_distribution == "CentOS" and ansible_distribution_major_version > "7") or
      (ansible_distribution == "RedHat")

- name: redhat | Installing FRR repository ignore SSL
  yum:
    name: "{{ frr_rpm_repository }}"
    state: present
    validate_certs: no
  become: true
  when:
    - (ansible_distribution == "CentOS" and ansible_distribution_major_version <= "7")

- name: redhat | Ensure Quagga is removed
  package:
    name: quagga
    state: absent
  become: true

- name: redhat | Installing FRR {{ frr_version }}
  yum:
    name:
      - frr
      - frr-pythontools
    state: present
  become: true
  notify:
    - restart frr

- name: redhat | Touch FRR reload log
  file:
    path: /var/log/frr/frr-reload.log
    state: touch
    owner: frr
    group: frr
    mode: 0644
    modification_time: preserve
    access_time: preserve
  become: true
