---
- name: system_tuning | Managing ipv4 Forwarding
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  become: true
  with_items:
    - net.ipv4.ip_forward
  when:
    - frr_ip_forwarding == True
  tags:
    - molecule-notest
- name: system_tuning | Managing ipv6 Forwarding
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  become: true
  with_items:
    - net.ipv6.conf.all.forwarding
  when:
    - frr_ipv6_forwarding == True
  tags:
    - molecule-notest
