---
# handlers file for ansible-frr
- name: full restart frr
  service:
    name: frr
    state: restarted
    enabled: true
  become: true
  when: frr_reload != true
  listen: "restart frr"

- name: reload frr
  service:
    name: frr
    state: reloaded
    enabled: true
  become: true
  when: frr_reload == true
  listen: "restart frr"
