---
- hosts: all
  tasks:
    - name: Update Apt Cache
      apt:
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: Ensure apt-utils is installed
      apt:
        name: apt-utils
        state: present
      become: true
      when: ansible_os_family == "Debian"
